spring:
  application:
    name: task-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: task-service
        health-check-path: /TASK-SERVICE/actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: task-service

server:
  port: 8083
  servlet:
    context-path: /TASK-SERVICE

logging:
  level:
    root: INFO
