spring:
  application:
    name: apigateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: apigateway-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - RewritePath=/api/tasks/(?<segment>/?.*), /TASK-SERVICE/api/tasks/${segment}

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - RewritePath=/api/projects/(?<segment>/?.*), /PROJECT-SERVICE/api/projects/${segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>/?.*), /USER-SERVICE/api/users${segment}


#  .\consul agent -dev --client=0.0.0.0

server:
  port: 8050

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.consul: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

